### PR TITLE
add mecab package

### PR DESCRIPTION
**Pull request by myoan**
I implement MeCab package.
please merge it.

### CODE REVIEW

**Comment by shinpei** [comment]
It contains binary files. plz remove binaries

**Comment by imasahiro** [comment]
this patch need to reconsider object layout.

**Comment by myoan** [comment]
I fixed object structure and remove *.tar.gz.

**Comment by shinpei** [comment]
plz fix followings.
- sfp[x].s --> sfp[x].asString
- 'konoha2' is contained in README

**Pull request merged**
